# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target '${POD_NAME}' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!

	# Pods for ${POD_NAME}
	pod 'Stinger'
	pod 'ReactiveObjC'
	pod 'YYModel'
	pod 'Masonry'
	pod 'SDWebImage'

  
  pod 'UITableView+FDTemplateLayoutCell', :git => 'https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git', :tag => '1.6'
  pod 'CTNetworking', :git => 'https://github.com/casatwy/CTNetworking.git', :tag => '15'
  pod 'ZKCategories', :git => 'https://github.com/kaiser143/ZKCategories.git', :commit => '44eb9dc904ab89277a9bb2487c87c608cf20e04f'
  pod 'ZKFoundation', :git => 'https://github.com/kaiser143/ZKFoundation.git', :commit => '2cc76c2f2453a1bd93dc0059bd6f80bae2680f27'

	target '${POD_NAME}Tests' do
  	inherit! :search_paths
  	# Pods for testing
  	${INCLUDED_PODS}
	end

	target '${POD_NAME}UITests' do
		inherit! :search_paths
		# Pods for testing
	end
end

post_install do |installer|
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Enterprise Name"
end
